spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev

server:
  port: 8081
  servlet:
    context-path: /

mybatis-plus:
  mapperLocations: classpath*:/mappers/**/*.xml
  typeAliasesPackage: com.saisaiwa.tspi.nas.domain
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

logging:
  level:
    com.saisaiwa.tspi.nas.mapper: debug
